id: IEA550892
legacy_id: P003122
ocr_import_info:
  bdrc_scan_id: W1KG22147
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T03:12:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T12:56:38.153306+00:00'
last_modified: 2022-08-31 21:02:54.463497
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22147
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22147
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞི་བྱེད་སྔ་ཕྱི་བར་གསུམ་གྱི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: མ་ཅིག་ལབ་ཀྱི་སྒྲོན་མ།
statistics:
  ocr_word_mean_confidence_index: 0.9119933783597126
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG22167:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22167
      total_pages: 812
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG22167.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9316264775127445
    legacy_id: v003
  I1KG22166:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22166
      total_pages: 832
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22166.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9285760899411111
    legacy_id: v002
  I1KG22171:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22171
      total_pages: 884
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG22171.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9337319151290521
    legacy_id: v007
  I1KG22168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22168
      total_pages: 840
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG22168.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9356285111721022
    legacy_id: v004
  I1KG22173:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22173
      total_pages: 872
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG22173.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9405893848464628
    legacy_id: v009
  I1KG22172:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22172
      total_pages: 910
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG22172.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9221594053693376
    legacy_id: v008
  I1KG22170:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22170
      total_pages: 1016
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG22170.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9206935164347555
    legacy_id: v006
  I1KG22174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22174
      total_pages: 846
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG22174.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9256169462625454
    legacy_id: v010
  I1KG22175:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22175
      total_pages: 752
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG22175.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.937252498982569
    legacy_id: v011
  I1KG22165:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22165
      total_pages: 886
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22165.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9258595049466881
    legacy_id: v001
  I1KG22177:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22177
      total_pages: 450
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG22177.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.6869245666707305
    legacy_id: v013
  I1KG22169:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22169
      total_pages: 846
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG22169.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9194841616624884
    legacy_id: v005
  I1KG22176:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22176
      total_pages: 838
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG22176.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9313804105804832
    legacy_id: v012
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
