id: IEA550892
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T03:17:29+00:00'
last_modified: '2022-06-07T17:44:40.158337+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22147
  title: ཞི་བྱེད་སྔ་ཕྱི་བར་གསུམ་གྱི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F1F0:
      image_group_id: I1KG22165
      title: ''
      total_pages: 886
      order: 1
      base_file: F1F0.txt
    99CC:
      image_group_id: I1KG22166
      title: ''
      total_pages: 832
      order: 2
      base_file: 99CC.txt
    E4DC:
      image_group_id: I1KG22167
      title: ''
      total_pages: 812
      order: 3
      base_file: E4DC.txt
    C801:
      image_group_id: I1KG22168
      title: ''
      total_pages: 840
      order: 4
      base_file: C801.txt
    5BA6:
      image_group_id: I1KG22169
      title: ''
      total_pages: 846
      order: 5
      base_file: 5BA6.txt
    B570:
      image_group_id: I1KG22170
      title: ''
      total_pages: 1016
      order: 6
      base_file: B570.txt
    F615:
      image_group_id: I1KG22171
      title: ''
      total_pages: 884
      order: 7
      base_file: F615.txt
    D0D6:
      image_group_id: I1KG22172
      title: ''
      total_pages: 910
      order: 8
      base_file: D0D6.txt
    5B93:
      image_group_id: I1KG22173
      title: ''
      total_pages: 872
      order: 9
      base_file: 5B93.txt
    EB1F:
      image_group_id: I1KG22174
      title: ''
      total_pages: 846
      order: 10
      base_file: EB1F.txt
    26BA:
      image_group_id: I1KG22175
      title: ''
      total_pages: 752
      order: 11
      base_file: 26BA.txt
    C46D:
      image_group_id: I1KG22176
      title: ''
      total_pages: 838
      order: 12
      base_file: C46D.txt
    8F8F:
      image_group_id: I1KG22177
      title: ''
      total_pages: 450
      order: 13
      base_file: 8F8F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
